# Generated by Django 4.2.5 on 2023-09-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='descriptions',
            field=models.TextField(default='Hello', max_length=500),
            preserve_default=False,
        ),
    ]
